/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Sep 11 15:03:53 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Status
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Case_StatusEnum {

    // Closed
    CLOSED("Closed"),
    // Escalated
    ESCALATED("Escalated"),
    // New
    NEW("New"),
    // Working
    WORKING("Working");

    final String value;

    private Case_StatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Case_StatusEnum fromValue(String value) {
        for (Case_StatusEnum e : Case_StatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
