/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Sep 11 15:03:53 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Product__c
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Case_ProductEnum {

    // GC1020
    GC1020("GC1020"),
    // GC1040
    GC1040("GC1040"),
    // GC1060
    GC1060("GC1060"),
    // GC3020
    GC3020("GC3020"),
    // GC3040
    GC3040("GC3040"),
    // GC3060
    GC3060("GC3060"),
    // GC5020
    GC5020("GC5020"),
    // GC5040
    GC5040("GC5040"),
    // GC5060
    GC5060("GC5060");

    final String value;

    private Case_ProductEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Case_ProductEnum fromValue(String value) {
        for (Case_ProductEnum e : Case_ProductEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
