/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Sep 11 15:03:53 EDT 2017
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist Type
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Case_TypeEnum {

    // Electrical
    ELECTRICAL("Electrical"),
    // Electronic
    ELECTRONIC("Electronic"),
    // Mechanical
    MECHANICAL("Mechanical"),
    // Other
    OTHER("Other"),
    // Structural
    STRUCTURAL("Structural");

    final String value;

    private Case_TypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Case_TypeEnum fromValue(String value) {
        for (Case_TypeEnum e : Case_TypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
